-- Logs begin at Tue 2021-09-07 20:37:23 CEST, end at Sat 2021-12-04 23:15:57 CET. --
Dec 04 23:11:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380647]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380647]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380647]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380647]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380647]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:24 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:24 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:24 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7156.
Dec 04 23:11:24 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:24 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380685]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:27 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:27 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:27 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7157.
Dec 04 23:11:27 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:27 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:29 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380724]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:29 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:29 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:29 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7158.
Dec 04 23:11:29 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:29 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380762]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:32 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:32 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:32 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7159.
Dec 04 23:11:32 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:32 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:34 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380805]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:34 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:34 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:34 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7160.
Dec 04 23:11:34 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:34 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:37 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380843]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:37 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:37 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:37 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7161.
Dec 04 23:11:37 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:37 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:39 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380882]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:39 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:39 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:39 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7162.
Dec 04 23:11:39 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:39 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:42 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380920]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:42 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:42 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:42 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7163.
Dec 04 23:11:42 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:42 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:44 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380958]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:44 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:44 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:44 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7164.
Dec 04 23:11:44 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:44 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:47 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3380999]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:47 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:47 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:47 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7165.
Dec 04 23:11:47 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:47 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:49 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381039]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:49 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:49 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:49 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7166.
Dec 04 23:11:49 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:49 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:52 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381077]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:52 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:52 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:52 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7167.
Dec 04 23:11:52 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:52 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:54 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381115]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:54 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:54 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:54 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7168.
Dec 04 23:11:54 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:54 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:57 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381157]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:57 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:57 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:57 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7169.
Dec 04 23:11:57 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:57 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at Object.openSync (node:fs:585:3)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at readFileSync (node:fs:453:35)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:11:59 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381196]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:11:59 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:11:59 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:11:59 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7170.
Dec 04 23:11:59 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:11:59 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:02 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381235]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:02 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:02 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:02 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7171.
Dec 04 23:12:02 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:02 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:04 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381273]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:04 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:04 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:04 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7172.
Dec 04 23:12:04 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:04 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:07 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381314]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:07 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:07 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:07 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7173.
Dec 04 23:12:07 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:07 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:09 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381352]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:09 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:09 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:09 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7174.
Dec 04 23:12:09 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:09 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:12 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381390]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:12 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:12 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:12 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7175.
Dec 04 23:12:12 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:12 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:14 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381428]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:14 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:14 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:14 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7176.
Dec 04 23:12:14 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:14 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:17 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381471]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:17 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:17 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:17 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7177.
Dec 04 23:12:17 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:17 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:19 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381509]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:19 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:19 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:19 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7178.
Dec 04 23:12:19 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:19 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:22 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381573]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:22 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:22 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:22 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7179.
Dec 04 23:12:22 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:22 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:24 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381611]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:24 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:24 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:24 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7180.
Dec 04 23:12:24 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:24 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:27 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381663]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:27 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:27 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:27 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7181.
Dec 04 23:12:27 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:27 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381749]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:30 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:30 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:30 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7182.
Dec 04 23:12:30 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:30 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at new GPHardware (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at Function.run (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at Function.start (/snap/gp-pi-sense-app/x6/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:32 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3381824]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:33 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:33 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:34 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7183.
Dec 04 23:12:34 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:34 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:34 gp-pi-sense-dev systemd[1]: Stopping Service for snap application gp-pi-sense-app.gp-pi-sense-app...
Dec 04 23:12:36 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Killing process 3382021 (node) with signal SIGKILL.[0m
Dec 04 23:12:36 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Succeeded.
Dec 04 23:12:36 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:45 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:50 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382241]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:50 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:50 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:50 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 1.
Dec 04 23:12:50 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:50 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382449]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:53 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:53 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:53 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 2.
Dec 04 23:12:53 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:53 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:55 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382492]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:55 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:55 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:55 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 3.
Dec 04 23:12:55 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:55 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at Object.openSync (node:fs:585:3)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at readFileSync (node:fs:453:35)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:12:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382531]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:12:58 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:12:58 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:12:58 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 4.
Dec 04 23:12:58 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:12:58 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:00 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382569]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:00 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:00 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:00 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 5.
Dec 04 23:13:00 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:00 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382609]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:03 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:03 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:03 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 6.
Dec 04 23:13:03 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:03 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:05 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382722]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:05 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:05 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:05 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 7.
Dec 04 23:13:05 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:05 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382761]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:08 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:08 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:08 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 8.
Dec 04 23:13:08 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:08 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:10 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382799]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:10 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:10 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:10 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 9.
Dec 04 23:13:10 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:10 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382837]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:13 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:13 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:13 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 10.
Dec 04 23:13:13 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:13 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:15 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382875]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:15 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:15 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:15 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 11.
Dec 04 23:13:15 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:15 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382916]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:18 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:18 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:18 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 12.
Dec 04 23:13:18 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:18 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:20 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382954]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:20 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:20 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:20 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 13.
Dec 04 23:13:20 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:20 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3382993]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:23 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:23 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:23 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 14.
Dec 04 23:13:23 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:23 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:25 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383031]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:25 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:25 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:25 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 15.
Dec 04 23:13:25 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:25 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383074]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:28 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:28 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:28 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 16.
Dec 04 23:13:28 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:28 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:30 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383114]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:30 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:30 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:31 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 17.
Dec 04 23:13:31 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:31 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383152]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:33 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:33 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:33 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 18.
Dec 04 23:13:33 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:33 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:35 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383191]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:35 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:35 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:36 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 19.
Dec 04 23:13:36 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:36 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:38 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383232]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:38 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:38 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:38 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 20.
Dec 04 23:13:38 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:38 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:41 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383372]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:41 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:41 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:41 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 21.
Dec 04 23:13:41 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:41 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:43 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383410]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:43 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:43 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:43 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 22.
Dec 04 23:13:43 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:43 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:46 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383492]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:46 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:46 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:46 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 23.
Dec 04 23:13:46 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:46 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:48 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383544]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:48 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:48 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:48 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 24.
Dec 04 23:13:48 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:48 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:51 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383604]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:51 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:51 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:51 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 25.
Dec 04 23:13:51 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:51 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:53 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383756]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:53 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:53 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:54 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 26.
Dec 04 23:13:54 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:54 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:56 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383797]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:56 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:56 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:56 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 27.
Dec 04 23:13:56 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:56 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at Object.openSync (node:fs:585:3)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at readFileSync (node:fs:453:35)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:13:58 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383837]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:13:58 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:13:58 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:13:59 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 28.
Dec 04 23:13:59 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:13:59 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:01 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383877]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:01 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:01 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:01 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 29.
Dec 04 23:14:01 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:01 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:03 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383929]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:03 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:03 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:04 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 30.
Dec 04 23:14:04 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:04 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:06 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3383971]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:06 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:06 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:06 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 31.
Dec 04 23:14:06 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:06 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:08 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384023]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:08 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:08 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:09 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 32.
Dec 04 23:14:09 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:09 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:11 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384065]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:11 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:11 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:11 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 33.
Dec 04 23:14:11 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:11 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:13 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384133]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:13 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:13 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:14 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 34.
Dec 04 23:14:14 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:14 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:16 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384202]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:16 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:16 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:16 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 35.
Dec 04 23:14:16 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:16 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:18 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384241]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:18 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:18 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:19 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 36.
Dec 04 23:14:19 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:19 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:21 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384281]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:21 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:21 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:21 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 37.
Dec 04 23:14:21 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:21 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:23 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384319]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:24 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:24 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:24 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 38.
Dec 04 23:14:24 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:24 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:26 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384469]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:26 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:26 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:26 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 39.
Dec 04 23:14:26 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:26 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:28 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384511]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:28 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:28 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:29 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 40.
Dec 04 23:14:29 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:29 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:31 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384550]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:31 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:31 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:31 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 41.
Dec 04 23:14:31 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:31 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:33 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384602]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:33 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:33 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:34 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 42.
Dec 04 23:14:34 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:34 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]: Error: EACCES: permission denied, open '/sys/class/graphics/fb0/name'
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at Object.openSync (node:fs:585:3)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at readFileSync (node:fs:453:35)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at GPLedMatrixController.findFrameBufferDevice (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:81:45)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at new GPLedMatrixController (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/controllers/led_matrix.controller.ts:73:10)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at new GPHardware (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:50:33)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at Function.run (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/hardware/hardware.ts:152:22)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at Function.start (/snap/gp-pi-sense-app/x7/lib/node_modules/gp-pi-sense-app/src/gp_pi_sense_app.ts:48:40)
Dec 04 23:14:36 gp-pi-sense-dev gp-pi-sense-app.gp-pi-sense-app[3384653]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 04 23:14:36 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 04 23:14:36 gp-pi-sense-dev systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185msnap.gp-pi-sense-app.gp-pi-sense-app.service: Failed with result 'exit-code'.[0m
Dec 04 23:14:36 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Scheduled restart job, restart counter is at 43.
Dec 04 23:14:36 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:14:36 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:15:32 gp-pi-sense-dev systemd[1]: Stopping Service for snap application gp-pi-sense-app.gp-pi-sense-app...
Dec 04 23:15:33 gp-pi-sense-dev systemd[1]: [0;1;39m[0;1;31m[0;1;39msnap.gp-pi-sense-app.gp-pi-sense-app.service: Killing process 3384756 (node) with signal SIGKILL.[0m
Dec 04 23:15:33 gp-pi-sense-dev systemd[1]: snap.gp-pi-sense-app.gp-pi-sense-app.service: Succeeded.
Dec 04 23:15:33 gp-pi-sense-dev systemd[1]: Stopped Service for snap application gp-pi-sense-app.gp-pi-sense-app.
Dec 04 23:15:52 gp-pi-sense-dev systemd[1]: Started Service for snap application gp-pi-sense-app.gp-pi-sense-app.
